// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG4xUenpcKRyLid-KVXjj2YDwXzf1ni9g',
    appId: '1:133185859842:web:1d74fa5fb5f48ed7f7121b',
    messagingSenderId: '133185859842',
    projectId: 'fbauth-97672',
    authDomain: 'fbauth-97672.firebaseapp.com',
    storageBucket: 'fbauth-97672.appspot.com',
    measurementId: 'G-ZMTDSLPNED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWaT608rdZrwo_37O-3fScBizIRjtq32I',
    appId: '1:133185859842:android:580fee1a90cd08edf7121b',
    messagingSenderId: '133185859842',
    projectId: 'fbauth-97672',
    storageBucket: 'fbauth-97672.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZSVelPBxioWocKclqVFFPY66c4D25030',
    appId: '1:133185859842:ios:a89ef62a041a2840f7121b',
    messagingSenderId: '133185859842',
    projectId: 'fbauth-97672',
    storageBucket: 'fbauth-97672.appspot.com',
    iosBundleId: 'com.example.fbAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZSVelPBxioWocKclqVFFPY66c4D25030',
    appId: '1:133185859842:ios:336572ac682b99a7f7121b',
    messagingSenderId: '133185859842',
    projectId: 'fbauth-97672',
    storageBucket: 'fbauth-97672.appspot.com',
    iosBundleId: 'com.example.fbAuth.RunnerTests',
  );
}
